export interface BankBrandItem {
  id: string;
  name: string;
  shortName: string;
  category: 'Banks' | 'Digital Bank' | 'E-Wallet' | 'International';
  brandColor: string;
  textColor?: string;
  suggestedInterestRate?: number;
  localAssetKey?: string;
  description?: string;
}

export const LOCAL_BRAND_ASSETS: { [key: string]: any } = {
  'gcash.png': require('../../public/walletimages/gcash.png'),
  'maya.png': require('../../public/walletimages/maya.png'),
  'gotyme.png': require('../../public/walletimages/gotyme.png'),
  'maribank.png': require('../../public/walletimages/maribank.png'),
  'paypal.png': require('../../public/walletimages/paypal.png'),
  'wise.png': require('../../public/walletimages/wise.png'),
};

export const PHILIPPINE_BANKS_AND_WALLETS: BankBrandItem[] = [
  // --- Popular E-Wallets ---
  {
    id: 'gcash.png',
    name: 'GCash',
    shortName: 'GCash',
    category: 'E-Wallet',
    brandColor: '#007DFE',
    localAssetKey: 'gcash.png',
    description: 'Leading Philippine mobile wallet',
  },
  {
    id: 'maya.png',
    name: 'Maya (PayMaya)',
    shortName: 'Maya',
    category: 'E-Wallet',
    brandColor: '#00D665',
    localAssetKey: 'maya.png',
    description: 'All-in-one wallet and crypto app',
  },
  {
    id: 'grabpay',
    name: 'GrabPay Philippines',
    shortName: 'GrabPay',
    category: 'E-Wallet',
    brandColor: '#00B14F',
    description: 'Everyday lifestyle wallet',
  },
  {
    id: 'shopeepay',
    name: 'ShopeePay',
    shortName: 'ShopeePay',
    category: 'E-Wallet',
    brandColor: '#EE4D2D',
    description: 'Shopee integrated digital wallet',
  },
  {
    id: 'coinsph',
    name: 'Coins.ph',
    shortName: 'Coins.ph',
    category: 'E-Wallet',
    brandColor: '#0070F3',
    description: 'Crypto & remittance wallet',
  },
  {
    id: 'palawanpay',
    name: 'PalawanPay',
    shortName: 'PalawanPay',
    category: 'E-Wallet',
    brandColor: '#008037',
    description: 'Pera padala & remittance wallet',
  },
  {
    id: 'cebuana',
    name: 'Cebuana Lhuillier (eCebuana)',
    shortName: 'Cebuana',
    category: 'E-Wallet',
    brandColor: '#BE1622',
    description: 'Microfinance & padala wallet',
  },
  {
    id: 'mlhuillier',
    name: 'M Lhuillier (ML Wallet)',
    shortName: 'MLhuillier',
    category: 'E-Wallet',
    brandColor: '#ED1C24',
    description: 'Remittance & bill payments',
  },

  // --- Major Philippine Universal / Commercial Banks ---
  {
    id: 'bdo',
    name: 'BDO Unibank',
    shortName: 'BDO',
    category: 'Banks',
    brandColor: '#002D72',
    description: 'Banco de Oro - Largest bank in PH',
  },
  {
    id: 'bpi',
    name: 'BPI (Bank of the Philippine Islands)',
    shortName: 'BPI',
    category: 'Banks',
    brandColor: '#A41D24',
    description: 'First bank in the Philippines & Southeast Asia',
  },
  {
    id: 'metrobank',
    name: 'Metrobank',
    shortName: 'Metrobank',
    category: 'Banks',
    brandColor: '#002D62',
    description: 'Metropolitan Bank and Trust Company',
  },
  {
    id: 'unionbank',
    name: 'UnionBank of the Philippines',
    shortName: 'UnionBank',
    category: 'Banks',
    brandColor: '#F47920',
    description: 'Pioneering digital universal bank',
  },
  {
    id: 'landbank',
    name: 'Landbank of the Philippines',
    shortName: 'Landbank',
    category: 'Banks',
    brandColor: '#006600',
    description: 'Official government development bank',
  },
  {
    id: 'securitybank',
    name: 'Security Bank',
    shortName: 'Security Bank',
    category: 'Banks',
    brandColor: '#008037',
    description: 'BetterBanking universal bank',
  },
  {
    id: 'rcbc',
    name: 'RCBC',
    shortName: 'RCBC',
    category: 'Banks',
    brandColor: '#003882',
    description: 'Rizal Commercial Banking Corporation',
  },
  {
    id: 'pnb',
    name: 'Philippine National Bank',
    shortName: 'PNB',
    category: 'Banks',
    brandColor: '#002060',
    description: 'Premier Philippine global bank',
  },
  {
    id: 'chinabank',
    name: 'China Bank (Chinabank)',
    shortName: 'China Bank',
    category: 'Banks',
    brandColor: '#A31F34',
    description: 'China Banking Corporation',
  },
  {
    id: 'eastwest',
    name: 'EastWest Bank',
    shortName: 'EastWest',
    category: 'Banks',
    brandColor: '#5A2582',
    description: 'Consumer-focused universal bank',
  },
  {
    id: 'psbank',
    name: 'PSBank',
    shortName: 'PSBank',
    category: 'Banks',
    brandColor: '#0054A6',
    description: 'Philippine Savings Bank (Metrobank Group)',
  },
  {
    id: 'dbp',
    name: 'DBP (Development Bank of the Philippines)',
    shortName: 'DBP',
    category: 'Banks',
    brandColor: '#0C2340',
    description: 'State-owned development bank',
  },
  {
    id: 'robinsonsbank',
    name: 'Robinsons Bank',
    shortName: 'Robinsons Bank',
    category: 'Banks',
    brandColor: '#00843D',
    description: 'Gokongwei Group commercial bank',
  },
  {
    id: 'bankofcommerce',
    name: 'Bank of Commerce',
    shortName: 'BankCom',
    category: 'Banks',
    brandColor: '#CE1126',
    description: 'San Miguel affiliate bank',
  },
  {
    id: 'maybank',
    name: 'Maybank Philippines',
    shortName: 'Maybank',
    category: 'Banks',
    brandColor: '#FFD100',
    textColor: '#000000',
    description: 'Maybank universal banking in PH',
  },

  // --- Philippine Digital Banks ---
  {
    id: 'gotyme.png',
    name: 'GoTyme Bank',
    shortName: 'GoTyme',
    category: 'Digital Bank',
    brandColor: '#00D2D2',
    localAssetKey: 'gotyme.png',
    suggestedInterestRate: 4.0,
    description: 'Gokongwei & Tyme high-interest digital bank',
  },
  {
    id: 'maribank.png',
    name: 'MariBank Philippines',
    shortName: 'MariBank',
    category: 'Digital Bank',
    brandColor: '#008080',
    localAssetKey: 'maribank.png',
    suggestedInterestRate: 2.5,
    description: 'Shopee Sea Group digital bank',
  },
  {
    id: 'seabank',
    name: 'SeaBank Philippines',
    shortName: 'SeaBank',
    category: 'Digital Bank',
    brandColor: '#FF5722',
    suggestedInterestRate: 4.5,
    description: 'High-yield daily interest digital bank',
  },
  {
    id: 'cimb',
    name: 'CIMB Bank Philippines',
    shortName: 'CIMB',
    category: 'Digital Bank',
    brandColor: '#7B0014',
    suggestedInterestRate: 2.5,
    description: 'All-digital mobile banking (GSave / UpSave)',
  },
  {
    id: 'tonik',
    name: 'Tonik Digital Bank',
    shortName: 'Tonik',
    category: 'Digital Bank',
    brandColor: '#8000FF',
    suggestedInterestRate: 4.0,
    description: 'First digital-only neobank in PH',
  },
  {
    id: 'unobank',
    name: 'Uno Digital Bank',
    shortName: 'Uno Bank',
    category: 'Digital Bank',
    brandColor: '#1856F3',
    suggestedInterestRate: 4.25,
    description: 'AI-first credit-led digital bank',
  },
  {
    id: 'diskartech',
    name: 'DiskarTech (by RCBC)',
    shortName: 'DiskarTech',
    category: 'Digital Bank',
    brandColor: '#00BCD4',
    suggestedInterestRate: 3.25,
    description: 'Taglish financial super-app by RCBC',
  },
  {
    id: 'komo',
    name: 'Komo (by EastWest)',
    shortName: 'Komo',
    category: 'Digital Bank',
    brandColor: '#00C9A7',
    suggestedInterestRate: 2.5,
    description: 'Digital banking service by EastWest Rural Bank',
  },
  {
    id: 'ownbank',
    name: 'OwnBank',
    shortName: 'OwnBank',
    category: 'Digital Bank',
    brandColor: '#E6B800',
    suggestedInterestRate: 6.0,
    description: 'High interest digital savings & deposits',
  },

  // --- International & Remittance ---
  {
    id: 'paypal.png',
    name: 'PayPal',
    shortName: 'PayPal',
    category: 'International',
    brandColor: '#003087',
    localAssetKey: 'paypal.png',
    description: 'Global online payments',
  },
  {
    id: 'wise.png',
    name: 'Wise (TransferWise)',
    shortName: 'Wise',
    category: 'International',
    brandColor: '#163300',
    localAssetKey: 'wise.png',
    description: 'International multi-currency account',
  },
];
